name = "pages-proxy-docker"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "dotink.tech"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "pages-proxy-docker"
routes = [
  { pattern = "docker.dotink.tech", custom_domain = true },
  { pattern = "quay.dotink.tech", custom_domain = true },
  { pattern = "gcr.dotink.tech", custom_domain = true },
  { pattern = "k8s-gcr.dotink.tech", custom_domain = true },
  { pattern = "k8s.dotink.tech", custom_domain = true },
  { pattern = "ghcr.dotink.tech", custom_domain = true },
  { pattern = "cloudsmith.dotink.tech", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"
